fastify/fastify-passport

package-lock.json
src/AuthenticationRoute.ts

Closes #24 to keep the TS dependency up to date. Not at all high priority, just figured I would fix it as I came across it.

Typescript 4.1.2

---

README.md
src/type-extensions.ts

Closes #51 . I tried this in my app and it seemed to work well enough for me! 

Export a type for users that can be declaration merged with

---

README.md

Fix syntax in docs

---

src/AuthenticationRoute.ts

Was using this locally and figured some folks might also appreciate being able to get very verbose but helpful logs when running at the trace level. Horray for pino being fast!

Add some tracing that's helpful when debugging which strategies are running

---

README.md

code errors fixed at README.md

---

README.md

Fix missing arrow for function in readme example

---

README.md

Adding a youtube tutorial

---

README.md

Add mandatory secureSession registration in readme example

---

package-lock.json
package.json
src/Authenticator.ts
src/session-managers/SecureSessionManager.ts
test/authorize.test.ts
test/decorators.test.ts
test/independent-strategy-instances.test.ts
test/multi-instance.test.ts
test/passport.test.ts
test/session-isolation.test.ts
test/session-serialization.test.ts
test/strategies-integration.test.ts
test/strategy.test.ts

feat: fastify v4 support

---

src/session-managers/SecureSessionManager.ts
src/strategies/SessionStrategy.ts
test/secure-session-manager.test.ts
test/session-strategy.test.ts

Solves this alert
https://lgtm.com/projects/g/fastify/fastify-passport/snapshot/cb23a31c4188c5cc28924c8e33c51686c3dbb215/files/src/strategies/SessionStrategy.ts?sort=name&dir=ASC&mode=list

throw error when no serialize /deserialize was passed to SessionStrategy or SecureSessionManager

---

README.md
test/passport.test.ts

chore: replace use of deprecated variadic `listen()`

---

.github/workflows/ci.yml
README.md
package.json

activate linting in ci workflow, fix CI Button link in readme

---

src/Authenticator.ts

use FastifyPluginAsync instead of FastifyPlugin

---

README.md

Update README.md spelling error

---

src/Authenticator.ts

Update Authenticator.ts spelling errors

---

jest.config.js

fix CI pipeline

---

.prettierrc
src/Authenticator.ts
src/CreateInitializePlugin.ts
test/csrf-fixation.test.ts
test/decorators.test.ts
test/helpers.ts
test/independent-strategy-instances.test.ts
test/multi-instance.test.ts
test/passport.test.ts
test/session-isolation.test.ts
test/session-serialization.test.ts
test/strategies-integration.test.ts

i dont know why prettier adds now commas thus failing currently the ci/cd pipeline, and i dont care. disabling trailing commas. 

fix: linting issues

---

src/session-managers/SecureSessionManager.ts
test/secure-session-manager.test.ts

This PR addresses this issue https://github.com/fastify/help/issues/932 in which `request.session.regenerate` will be called twice if `this.clearSessionOnLogin` is set to true (the default). This results in polluting the sessionStore with extra sessions.

#932 fix:  avoid multiple calls to regenerate

---

jest.config.js

chore: add missing `use strict` directive

---

src/AuthenticationRoute.ts

See https://github.com/fastify/fastify-helmet/issues/236

refactor(authenticationroute): replace `typeof` undefined check

---

test/passport.test.ts

test: prefix unused params with underscores

---

.github/workflows/ci.yml

See https://github.com/fastify/fastify/issues/5354. This is a batch PR, so may have some issues. Please review changes.

ci: remove master branch support
