fastify/fastify-passport

- .eslintignore
- .eslintrc.js
- .github/workflows/ci.yml
- package-lock.json
- package.json
- src/AuthenticationRoute.ts
- src/CreateInitializePlugin.ts
- test/helpers.ts
- tsconfig.eslint.json
- tsconfig.json
- Fixes eslint path issues (closes https://github.com/fastify/fastify-passport/issues/5)
- Updates fastify-plugin in the package-lock.json to fix export default issue (ref: https://github.com/fastify/fastify-plugin/pull/106)
- Uses `import flash = require('fastify-flash')` to make it work with both esModuleInterop settings (ref: https://github.com/fastify/fastify-helmet/pull/96)
> Removes harmful tsconfig settings

- README.md
As discussed in #30, here are some possible improvements to the docs for the authenticate function.
I added the signature using just the parameter names, and added some `|`'s and `?`'s to represent possible alternative values. I also added a slightly more in depth explanation on each parameter. Finally, I also expanded the example to include all parameters, and to see some more of them in action. Let me know what you guys think.
> Improve docs for "authenticate" function

- src/CreateInitializePlugin.ts
We're decorating the request with the Authenticator object responsible for managing passport authentication mostly so that request handlers installed by the Authenticator can ensure they're operating in an encapsulation context where the rest of the fastify-passport plugin was initialized correctly. Fastify has deprecated reference decorators to avoid accidental data-sharing between requests or memory leaks. In this case, I think we actually *want* to share this piece of data (the Authenticator instance) between requests, so we use the escape hatch to avoid the deprecation warning by using a getter decorator to return it.
An alternative might be to set a scalar sigil of some sort on the request, but I feel like that's less clear, or to use an onRequest hook, which is slower just to avoid …
> Fix FSTDEP006 by exposing the Authenticator object using a getter decorator

- README.md
- src/Authenticator.ts
- test/helpers.ts
- test/session-serialization.test.ts
I missed this nuance during the original porting -- returning false or null from a user deserializer means something special. It means the user not being found is not an error condition but just means the session has out-of-date data, and should be logged out. See https://github.com/jaredhanson/passport/issues/6 for the original context on how this is a thing in passport. This recreates that functionality and tests it!
> Implement and document handled deserialization failures

- package-lock.json
- package.json
- src/index.ts
- test/esm/default-esm-export.mjs
- test/esm/esm.test.ts
- test/esm/named-esm-export.mjs
> fix: fastifyPassport is undefined when use native ESM import

- package-lock.json
- package.json
Following the discussion in #91, this PR switches `fastify-secure-session` to a dev dep.
Would be great to have a published release soon :)!
> chore(npm): switch fastify-secure-session to a dev dep

- README.md
- src/Authenticator.ts
- src/CreateInitializePlugin.ts
- src/decorators/is-authenticated.ts
- src/decorators/login.ts
- src/decorators/logout.ts
- src/index.ts
- src/strategies/SessionStrategy.ts
- test/multi-instance.test.ts
This adds support for registering `fastify-passport` more than once in the same application, where each instance stores its logged in user at a different decorated property on the request. This is useful for adding say an admin only area to an application that already has user login set up.
> Multiple disjoint registered instance support

- README.md
- src/AuthenticationRoute.ts
- src/Authenticator.ts
- test/helpers.ts
- test/independent-strategy-instances.test.ts
- test/passport.test.ts
This allows for running authentication with ephemeral strategies you don't want to register into the global namespace, or for simultaneous asynchronous authentications using the same strategy with different configurations. My use case specifically is that I want some users of my application to bring their own credentials -- instead of using one fixed oauth access token for a given integration, users should be able to supply their own, and we'll use it at runtime instead of the fixed one.
This means that for a given request we need to be able to use either the fixed strategy registered with the authenticator at server boot, or an ephemeral one created using the request context for just that request. It's important that the strategy not be registered into the global list of strategies so it …
> Add support for authenticating with already-instantiated strategies.

- .github/dependabot.yml
- .github/workflows/ci.yml
This PR contains various improvements around dependabot and the build:
- use Node shorthand for CI
- add Node 16 to CI
- use setup-node action builtin cache
- use automerge action v3. this is to avoid too many dependabot bumps to github actions
- remove unnecessary ignores in dependabot config file: when referencing semver major/minor/whatever, dependabot will already use whatever is latest within the specified range. i.e if you use action@v3, dependabot will us whatever v3 is latest (e.g. v3.0.2)
All the above changes could be made throughout the whole set of plugins. I know that some time ago @Fdawgs did the dependabot ignore change across many repos. Now that change turned out to be unnecessary.
> chore: build and dependabot improvements

- README.md
- src/AuthenticationRoute.ts
- [] tests and/or benchmarks are included
> Fixes Issue #595 - Add state prop to AuthenticateOptions interface

- src/AuthenticationRoute.ts
- src/strategies/base.ts
- test/strategy.test.ts
Before this change, strategies that throw errors (or return promises which throw errors) wouldn't trigger the fastify error handling. Strategies which returned promises that then rejected would trigger uncaughPromiseRejection events as well.
This issue stems from the strange API that passport requires for strategies born in the callback era, where strategies get told to run and are expected to call back into the fastify-passport handling by calling `this.error` or `this.success` or what have you. If the strategy throws unexpectedly though, we didn't catch that and now we do.
> Catch unexpected errors during strategy execution and dispatch through the fastify error stack

- src/strategies/base.ts
- test/strategy.test.ts
* Changed the Strategy.fail() declaration to allow for overloading.
* Added tests to verify Strategy.fail() overloading
Fixes #627
> Strategy.fail() overloading fix

- package-lock.json
- package.json
- test/strategies-integration.test.ts
Adds a test to show that this works with node-openid-client passport strategy.
Supersedes #535 
Closes #491
> feat: openid-client support

- package-lock.json
- package.json
- src/Authenticator.ts
- test/authorize.test.ts
Fixes the authorize typings as they were lacking the return type in the function overloads.
extracted from #646 
> fix authorize typings

- jest.config.js
- package-lock.json
- package.json
This changes are needed to support latest Fastify (v4.19.0). See https://github.com/fastify/fastify/issues/4873 for more details
> Bump typescript dependency

- jest.config.js
- package-lock.json
- Changed `collectCoverage` option for Jest to collect coverage. Ref: https://jestjs.io/docs/configuration#collectcoverage-boolean
- Updated `package-lock.json` to solve `Browserslist: caniuse-lite is outdated.` warnings.
> chore: enable coverage

- jest.config.js
- package-lock.json
- package.json
Currently #972 can not be merged, because we replaced in latest fastify tiny-lru with toad-cache. 
Remark: package-lock.json was generated with npm 6.14.18 and node 14.
> ci: fix tiny-lru issue

- README.md
- src/AuthenticationRoute.ts
- src/decorators/login.ts
- src/session-managers/SecureSessionManager.ts
- test/secure-session-manager.test.ts
https://github.com/fastify/fastify-passport/issues/1141
Request login method started to accept `keepSessionInfo` boolean parameter. In a moment when we are going to perform cleanup session info, with specified keepSessionInfo=true param, we prevent clearing session on login. 
See the description of the same functionality on original passport project: https://medium.com/passportjs/fixing-session-fixation-b2b68619c51d 
> support keeping session info during session regenerate on req.login

- src/AuthenticationRoute.ts
- test/passport.test.ts
See https://github.com/fastify/fastify-static/pull/407. This is a batch PR, so may have some issues. Please review changes.
> perf: use `node:` prefix to bypass require.cache call for builtins

- .github/dependabot.yml
The commit history of this repo is a madness:
- https://github.com/fastify/fastify-passport/commits/main/
let's fix it by setting a better version strategy: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy
> fix: dependabot updates

- README.md
See https://github.com/fastify/deepmerge/pull/54
> docs(readme): use simple english

- .github/workflows/ci.yml
This is a batch PR. This change stops security tools like step-security from complaining.
> ci: set permissions at workflow level
